
import type { Metadata } from "next";
import { Inter, Work_Sans } from "next/font/google";
import "./globals.css";
import { AOSInit } from "@/components/Aos";

const inter = Work_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MenuTech The Best Choice for YOU",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <AOSInit />
      </body>
    </html>
  );
}
